name: automerge
on:
    pull_request_target:
        types:
            - assigned
            - unassigned
            - labeled
            - unlabeled
            - opened
            - edited
            - closed
            - reopened
            - synchronize
            - converted_to_draft
            - ready_for_review
            - locked
            - unlocked 
            - review_requested 
            - review_request_removed 
            - auto_merge_enabled 
            - auto_merge_disabled

jobs:
    automerge:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: "${{ secrets.GH_ACTIONS_TOKEN }}"
        steps:
            - run: echo testing ${{ github.event.pull_request.merge_commit_sha }}
