on:
    workflow_dispatch:
    workflow_call:

env:
    PLUGIN_NAME: obsidian-overload

permissions:
    contents: write
    pull-requests: write

name: publish

jobs:
    publish:
        runs-on: ubuntu-latest
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        steps:
            # The logic below handles the npm publication:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: "https://registry.npmjs.org"
            - run: |
                  cat /home/runner/work/_temp/.npmrc
            - run: npm ci
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
