on:
    workflow_dispatch:

    push:
        branches:
            - "main"

permissions:
    contents: write
    pull-requests: write

name: release-please

jobs:
    release-please:
        runs-on: ubuntu-latest
        outputs:
            release_created: ${{ steps.release.outputs.release_created }}
            upload_url: ${{ steps.release.outputs.upload_url }}
            tag_name: ${{ steps.release.outputs.tag_name }}
            pr: ${{ steps.release.outputs.pr }}
        steps:
            - uses: google-github-actions/release-please-action@v3
              env:
                  GITHUB_TOKEN: "${{ secrets.GH_ACTIONS_TOKEN }}"
              id: release
              with:
                  command: manifest
            - run: echo ${{ steps.release.outputs.pr }}
    publish:
        needs: release-please
        if: ${{ needs.release-please.outputs.release_created }}
        uses: javalent/workflows/.github/workflows/publish.yml@main
        secrets: inherit
