on:
    workflow_dispatch:
        inputs:
            module:
                required: true
                description: Module to upgrade
                type: string
    workflow_call:
        inputs:
            module:
                required: true
                type: string

name: upgrade

jobs:
    upgrade:
        runs-on: ubuntu-latest
        outputs:
            committed: ${{ steps.commit.outputs.committed }}

        env:
            GITHUB_TOKEN: "${{ secrets.GH_ACTIONS }}"
        steps:
            # The logic below handles the npm publication:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GH_ACTIONS }}
                  repository: "javalent/obsidian-overload"
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: "https://registry.npmjs.org"
            - run: npm i ${{inputs.module}}@latest
            - uses: EndBug/add-and-commit@v9
              id: commit
              with:
                  default_author: github_actions
                  message: "feat: Upgrading ${{ inputs.module }} to latest"
              env:
                  GITHUB_TOKEN: "${{ secrets.GH_ACTIONS }}"
